### ISSUE TITLE
Cannot change color with parameter "color " when plotting band structure

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [romerogroup/pyprocar#115]
```python
import pyprocar
import os

dir=os.path.dirname(os.getcwd())
band_dir=f"{dir}{os.sep}yifan_test{os.sep}band"
pband_dir=f"{dir}{os.sep}yifan_test{os.sep}pband"

#ebs_plot = pyprocar.bandsplot(code='vasp', dirname = band_dir, mode='parametric', elimit=[-5,5], orbitals=[4,5,6,7,8], show=False)
#pyprocar.bandsplot(code='vasp', dirname = pband_dir, mode='plain', elimit=[-5,5], color='k',ax=ebs_plot.ax, show =True)
pyprocar.bandsplot(code='vasp',dirname=band_dir,elimit=[-2,2],mode='plain',color='green')
``` 
I used above command and my figure still make blue band structure. Can someone help me solve this problem? Thank you!
 
![test_yf](https://github.com/romerogroup/pyprocar/assets/122458488/a65810bc-8bbf-4845-b97b-1ac9c35bf1f6)

**Comment by PolyuWeldingSpock** [comment]
I upload my file with Onedrive link since it is too large.
https://1drv.ms/u/s!AtO91yh6_pLhg7FyXhBANFgrm_STRg?e=MTw89y

**Comment by PolyuWeldingSpock** [comment]
I also found that 'color' parameter seems to be not defined either in documentation or in source code.
https://romerogroup.github.io/pyprocar/user-guide/bands.html

**Comment by lllangWV** [comment]
Hey,

 you are right this is an issue. I am currently trying to resolve this. We are trying to move all the plotting options into configuration files. Then if you need to change a default value, you will be able to just add the keyword argument to the method call. I'll try to get this done this week and get back to you.

Logan Lang

**Comment by PolyuWeldingSpock** [comment]
> Hey,
> 
> you are right this is an issue. I am currently trying to resolve this. We are trying to move all the plotting options into configuration files. Then if you need to change a default value, you will be able to just add the keyword argument to the method call. I'll try to get this done this week and get back to you.
> 
> Logan Lang

Thanks for your effort. I have used other method to change the color. Here is an example of my plot script:
```python
ebs_plot1 = pyprocar.bandsplot(code='vasp', atoms=atoms, orbitals=orbitals, dirname = band_1_dir, mode='plain', elimit=[-0.5,2.2], show=False,fermi=0.3022)

for handle in ebs_plot1.handles:
    handle[0].set_color('black')
    handle[0].set_linewidth(0.8)
```

**Comment by lllangWV** [comment]
Hey, 

I updated bandsplot and added a configuration file to control various plotting elements. These configs setting can be passed to bandsplot. If you want to see the various config parameters and their description set print_plot_opts=True in bandsplot.

Here is the updated plot for the following code:
ebs_plot = pyprocar.bandsplot(code='vasp', dirname = vasp_data_dir, mode='parametric', elimit=[-5,5], orbitals=[4,5,6,7,8], show=False)
pyprocar.bandsplot(code='qe', dirname = qe_data_dir, mode='plain', elimit=[-5,5], color='black',ax=ebs_plot.ax, show =True)

![image](https://github.com/romerogroup/pyprocar/assets/120115419/4a23b924-1856-4eee-8a6b-649fbf88064d)


These changes are in the main branch on Git Hub. Sometime this week, I will update pypi and anaconda.

Let me know if you have any other issues.

Logan Lang

**Comment by PolyuWeldingSpock** [comment]
> Hey,
> 
> I updated bandsplot and added a configuration file to control various plotting elements. These configs setting can be passed to bandsplot. If you want to see the various config parameters and their description set print_plot_opts=True in bandsplot.
> 
> Here is the updated plot for the following code: ebs_plot = pyprocar.bandsplot(code='vasp', dirname = vasp_data_dir, mode='parametric', elimit=[-5,5], orbitals=[4,5,6,7,8], show=False) pyprocar.bandsplot(code='qe', dirname = qe_data_dir, mode='plain', elimit=[-5,5], color='black',ax=ebs_plot.ax, show =True)
> 
> ![image](https://user-images.githubusercontent.com/120115419/257134604-4a23b924-1856-4eee-8a6b-649fbf88064d.png)
> 
> These changes are in the main branch on Git Hub. Sometime this week, I will update pypi and anaconda.
> 
> Let me know if you have any other issues.
> 
> Logan Lang

Excellent! Thanks for your effort!
 I also want to know that if new code could change the style of fermi level which is default in blue and dashed line?

**Comment by lllangWV** [comment]
It should have been able to, but I set the plotting options in the wrong place such that they can't be updated. I will fix this today
