### ISSUE TITLE
Issue in plotting spin texture with fermi2d()

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [romerogroup/pyprocar#124]
Hi, developers of Pyprocar

recently I have used Pyprocar to plot spin texture for visualizing rashba effect like examples of Pyprocar documentation. But I have several problems about Pyprocar.

1. I installed pyprocar `pip install pyprocar`. Then I plotted pyprocar with this command:
```python
import pyprocar
import matplotlib.pyplot as plt

data_dir='.'
plt = pyprocar.fermi2D(code='vasp', energy=0.95, spin_texture=True, no_arrow=True, arrow_projection='x', dirname=data_dir, exportplt=True,color_bar=True)

plt.clim(vmin=-0.1, vmax=0.1)

plt.savefig('x.pdf', dpi=1000)

plt.show()

``` 

Then error occurred
```python
|  _ \ _   _|  _ \ _ __ ___   ___ __ _ _ __ 
| |_) | | | | |_) | '__/ _ \ / __/ _` | '__|
|  __/| |_| |  __/| | | (_) | (_| (_| | |   
|_|    \__, |_|   |_|  \___/ \___\__,_|_|
       |___/
A Python library for electronic structure pre/post-processing.

Version 6.0.0 created on Jun 10th, 2021

Please cite:
 Uthpala Herath, Pedram Tavadze, Xu He, Eric Bousquet, Sobhit Singh, Francisco Muñoz and Aldo Romero.,
 PyProcar: A Python library for electronic structure pre/post-processing.,
 Computer Physics Communications 251 (2020):107080.


Developers:
- Francisco Muñoz
- Aldo Romero
- Sobhit Singh
- Uthpala Herath
- Pedram Tavadze
- Eric Bousquet
- Xu He
- Reese Boucher
- Logan Lang
- Freddy Farah
    
dirname         :  .
bands           :  None
atoms           :  None
orbitals        :  None
spin comp.      :  None
energy          :  0.95
rot. symmetry   :  1
origin (trasl.) :  [0, 0, 0]
rotation        :  [0, 0, 0, 1]
save figure     :  None
spin_texture    :  True

            --------------------------------------------------------
            There are additional plot options that are defined in a configuration file. 
            You can change these configurations by passing the keyword argument to the function
            To print a list of plot options set print_plot_opts=True

            Here is a list modes : plain , plain_bands , parametric
            --------------------------------------------------------
            
_____________________________________________________
Useful band indices for spin-0 : [0 1]
Traceback (most recent call last):
  File "/media/polyucmp/DATA/BIAN_Tieyuan/yinjun/plot_spin-new/n4-R-band-xy-new/CBM/plot_spin.py", line 14, in <module>
    plt = pyprocar.fermi2D(code='vasp', energy=0.95, spin_texture=True, no_arrow=True, arrow_projection='x', dirname=data_dir, exportplt=True,color_bar=True)
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/pyprocar/lib/python3.10/site-packages/pyprocar/scripts/scriptFermi2D.py", line 214, in fermi2D
    fs = FermiSurface(symm.kpoints, symm.bands, symm.character,  
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/pyprocar/lib/python3.10/site-packages/pyprocar/core/fermisurface.py", line 80, in __init__
    self.update_config(kwargs) 
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/pyprocar/lib/python3.10/site-packages/pyprocar/core/fermisurface.py", line 467, in update_config
    self.plot_opt[key]['value']=value
KeyError: 'color_bar'

```

After I deleted 'color_bar=True',,error disappeared. Spin texture was successfully plotted:
![x](https://github.com/romerogroup/pyprocar/assets/122458488/0138d134-9040-428d-bd26-e9a3282cfdf3)
It seems that 'color_bar' may have some issues. Hope developers could help. Thanks in advance! 1.zip is the files containing OUTCAR POSCAR and PROCAR.
[1.zip](https://github.com/romerogroup/pyprocar/files/12272663/1.zip)

2. Another issue is that the `translate` and `rotation`.  I have calculated spin texture in x-z plane. Then I tried to translate and rotate it into x-y plane for Pyprocar to plot. 
I used this command:
```python
import pyprocar
import matplotlib.pyplot as plt

data_dir='.'
spin_plot=pyprocar.fermi2D(code='vasp', energy=0.95, spin_texture=True, no_arrow=True, arrow_projection='y', dirname=data_dir, exportplt=True, translate=[0.25,0,0.25],rotation=[90,1,0,0])

plt.savefig('y.tif')

plt.show()

```
But it showed this error:
```python
  _ \ _   _|  _ \ _ __ ___   ___ __ _ _ __ 
| |_) | | | | |_) | '__/ _ \ / __/ _` | '__|
|  __/| |_| |  __/| | | (_) | (_| (_| | |   
|_|    \__, |_|   |_|  \___/ \___\__,_|_|
       |___/
A Python library for electronic structure pre/post-processing.

Version 6.0.0 created on Jun 10th, 2021

Please cite:
 Uthpala Herath, Pedram Tavadze, Xu He, Eric Bousquet, Sobhit Singh, Francisco Muñoz and Aldo Romero.,
 PyProcar: A Python library for electronic structure pre/post-processing.,
 Computer Physics Communications 251 (2020):107080.


Developers:
- Francisco Muñoz
- Aldo Romero
- Sobhit Singh
- Uthpala Herath
- Pedram Tavadze
- Eric Bousquet
- Xu He
- Reese Boucher
- Logan Lang
- Freddy Farah
    
dirname         :  .
bands           :  None
atoms           :  None
orbitals        :  None
spin comp.      :  None
energy          :  0.95
rot. symmetry   :  1
origin (trasl.) :  [0.25, 0, 0.25]
rotation        :  [90, 0, 0, 1]
save figure     :  None
spin_texture    :  True

            --------------------------------------------------------
            There are additional plot options that are defined in a configuration file. 
            You can change these configurations by passing the keyword argument to the function
            To print a list of plot options set print_plot_opts=True

            Here is a list modes : plain , plain_bands , parametric
            --------------------------------------------------------
            
_____________________________________________________
Useful band indices for spin-0 : [0 1]
Traceback (most recent call last):
  File "/media/polyucmp/DATA/BIAN_Tieyuan/yinjun/plot_spin-new/n4-R-new/test/plot_spin.py", line 14, in <module>
    spin_plot=pyprocar.fermi2D(code='vasp', energy=0.95, spin_texture=True, no_arrow=True, dirname=data_dir, exportplt=True, translate=[0.25,0,0.25],rotation=[90,0,0,1])
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/pyprocar/lib/python3.10/site-packages/pyprocar/scripts/scriptFermi2D.py", line 222, in fermi2D
    fs.spin_texture(sx=symm.sx, 
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/pyprocar/lib/python3.10/site-packages/pyprocar/core/fermisurface.py", line 329, in spin_texture
    bnew.append(griddata((x, y), band, (xnew, ynew), method="cubic"))
  File "/home/polyucmp/.local/lib/python3.10/site-packages/scipy/interpolate/_ndgriddata.py", line 277, in griddata
    ip = CloughTocher2DInterpolator(points, values, fill_value=fill_value,
  File "interpnd.pyx", line 915, in scipy.interpolate.interpnd.CloughTocher2DInterpolator.__init__
  File "_qhull.pyx", line 1827, in scipy.spatial._qhull.Delaunay.__init__
  File "_qhull.pyx", line 353, in scipy.spatial._qhull._Qhull.__init__
scipy.spatial._qhull.QhullError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing:  | qhull d Qt Qc Qz Q12 Qbb
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 810020071  delaunay  Qtriangulate  Qcoplanar-keep  Qz-infinity-point
  Q12-allow-wide  Qbbound-last  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 0.35  Error-roundoff 4.9e-16  _one-merge 3.4e-15
  Visible-distance 9.8e-16  U-max-coplanar 9.8e-16  Width-outside 2e-15
  _wide-facet 5.9e-15  _maxoutside 3.9e-15

The input to qhull appears to be less than 3 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p1(v4): 0.039     0 0.0039
- p10(v3):  0.18     0  0.35
- p9(v2):  0.35     0  0.32
- p0(v1):     0     0     0

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 4.9e-16.  The center point, facets and distances
to the center point are as follows:

center point   0.1417        0   0.1689

facet p10 p9 p0 distance=    0
facet p1 p9 p0 distance=    0
facet p1 p10 p0 distance=    0
facet p1 p10 p9 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:         0    0.3519  difference= 0.3519
  1:         0         0  difference=    0
  2:         0    0.3519  difference= 0.3519

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 4.9e-16.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.
```
I solved this problem by recalculating in x-y plane so it did not need rotation. But considering this existing problem and recalculating always need more time. I sincerely hope developers could help solve this issue. Here is my files calculated in x-z plane (2.zip). 
[2.zip](https://github.com/romerogroup/pyprocar/files/12272750/2.zip)

**Comment by lllangWV** [comment]
Hey PolyuWeldingSpock,

1. For the first issue, I updated pyprocar to store plotting configurations in a .yml. I included the following message that tells you how to see all the plot options. I also updated the doc, so you can find them there as well https://romerogroup.github.io/pyprocar/api/cfg/index.html. I changed color_bar argument to **plot_color_bar**.
           There are additional plot options that are defined in a configuration file. 
            You can change these configurations by passing the keyword argument to the function
            To print a list of plot options set print_plot_opts=True

2. I need more time to look into this problem. With a quick glance, I believe the issue is that I reduced the kmesh to only be a k_z plane, which if your kpoints are in the another plane the algorithm won't work. Thank you for sending the file, it will be helpful to come up with a solution.

Logan Lang

**Comment by PolyuWeldingSpock** [comment]
> Hey PolyuWeldingSpock,
> 
> 1. For the first issue, I updated pyprocar to store plotting configurations in a .yml. I included the following message that tells you how to see all the plot options. I also updated the doc, so you can find them there as well https://romerogroup.github.io/pyprocar/api/cfg/index.html. I changed color_bar argument to **plot_color_bar**.
>    There are additional plot options that are defined in a configuration file.
>    You can change these configurations by passing the keyword argument to the function
>    To print a list of plot options set print_plot_opts=True
> 2. I need more time to look into this problem. With a quick glance, I believe the issue is that I reduced the kmesh to only be a k_z plane, which if your kpoints are in the another plane the algorithm won't work. Thank you for sending the file, it will be helpful to come up with a solution.
> 
> Logan Lang

Hi, Thanks for your kind reply. It helps a lot.

However, I have a question about configuration file fermi_surface_2d.yml. I saw that
```python
dpi
description: The dpi value to save the image as
value: figure
```
I am curious about that how to set this dpi value 'dpi=***'. Should it be a numeric value such as 300,400? I do not understand meaning of `value: figure` .

**Comment by lllangWV** [comment]
Hey!

1. For the first issue, I did not allow the user to be able to change the clim for spin texture. I'll add this in, this should be quick.

2. The rotation issue is a little more involved, for now, I would just stick with 2d kmesh in  x-y plane. I still need more time for that. However, the projection issue is because I only allowed the user to select the projection for arrows and not for the scatter plot. I am going to change this and add a keyword argument called 'spin_projection' which will select the projection you want for both the arrows and the scatter plots.


I will push these changes later today to the dev branch
![image](https://github.com/romerogroup/pyprocar/assets/120115419/2af5ff44-4879-4d1b-8823-055afce2f0b2)

![image](https://github.com/romerogroup/pyprocar/assets/120115419/4045df15-29b2-4e38-9be2-03856a3862c4)

**Comment by PolyuWeldingSpock** [comment]
> Hey!
> 
> 1. For the first issue, I did not allow the user to be able to change the clim for spin texture. I'll add this in, this should be quick.
> 2. The rotation issue is a little more involved, for now, I would just stick with 2d kmesh in  x-y plane. I still need more time for that. However, the projection issue is because I only allowed the user to select the projection for arrows and not for the scatter plot. I am going to change this and add a keyword argument called 'spin_projection' which will select the projection you want for both the arrows and the scatter plots.
> 
> I will push these changes later today to the dev branch ![image](https://user-images.githubusercontent.com/120115419/258871505-2af5ff44-4879-4d1b-8823-055afce2f0b2.png)
> 
> ![image](https://user-images.githubusercontent.com/120115419/258871843-4045df15-29b2-4e38-9be2-03856a3862c4.png)

That is very great new! Thanks for your effort!
