### ISSUE TITLE
Can't use Keyword Arguments in pyprocar.bandsplot

### ISSUE THREAD

**Issue by ThoCheChen** [romerogroup/pyprocar#131]
Hi pyprocar developers,

I had just installed pyprocar **v6.1.4** and was going through the band structure tutorial in this link: https://romerogroup.github.io/pyprocar/user-guide/bands.html

However I encountered several issues, such as not being able to specify the keyword arguments. For example, when using pyprocar.bandsplot, I can't specify **outcar='OUTCAR'** and **kdirect=False** as I will get **KeyError: 'outcar'** or **KeyError: 'kdirect'**.

Also, pyprocar.bandsplot only searches for PROCAR and setting procar='random_name' will also lead to error.   

pyprocar.filter('PROCAR','PROCAR-up',spin=[0])
pyprocar.filter('PROCAR','PROCAR-down',spin=[1])
pyprocar.bandsplot('PROCAR-up',...) #The program will not read 'PROCAR-up'

Can you help me with this issue?

**Comment by lllangWV** [comment]
Hello!

I apologize, in the most recent version we changed the method how to plot the spin up and down channels. I forgot to update this part of the documentation. I will update it today. I recommend you to look at the example gallery, there are examples for the plotting of spin-polarized calculations.

To plot the channels separately use the following:
pyprocar.bandsplot(code='vasp',dirname='bands',mode='plain', spins=[0]) # plots the spin up channel
pyprocar.bandsplot(code='vasp',dirname='bands',mode='plain', spins=[1]) # plots the spin down channel

code specifies the DFT code you are using. dirname specifies the directory of the calculation

To plot the channels together use the following:
pyprocar.bandsplot(code='vasp',dirname='bands',mode='plain', spins=[0,1])


Another option is to use an older version pyprocar==5.6.6, then the code you used should work. Here is the documentation for version 5.6.6:
https://romerogroup.github.io/pyprocar5.6.6/

Logan Lang

**Comment by ThoCheChen** [comment]
Hi Logan,

Thank you for getting back to my question.

So how about other flags like the one I mentioned **kdirect=False** for **v6.1.4**? I obtained **KeyError** when setting that flag.

**Comment by ThoCheChen** [comment]
Hi Logan, 

I have just tried the older version pyprocar **v5.6.6** and I can use the flags as mentioned earlier. But I hope that the developer team can include these flags also in future versions.

Thank you.

**Comment by ahromero** [comment]
ThoCheChen

Thanks for your interest.. we are in the process of having a major release, with more functionalities, better interface and hopefully even easier to use…. This should happen in the next few weeks

Thanks


______________________________________::::__________________________________________
Prof. Aldo Humberto Romero
Director Research Computing, West Virginia University
Eberly Family Distinguished Professor
Fellow American Physical Society
Editor Physica B, Assistant Editor EPJB, Editor Frontiers in Physics
Section Editor Papers in Physics
Member of the Editorial Board of  “Materials” and “Symmetry Physics”

Physics and Astronomy Department
West Virginia University
135 Willey Street, PO Box 6315
111 White Hall
Morgantown, WV 26506
Phone:  304-293-6317
Fax:  304-293-5732
email: ***@***.***


From: ThoCheChen ***@***.***>
Date: Sunday, September 24, 2023 at 11:11 AM
To: romerogroup/pyprocar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [romerogroup/pyprocar] Can't use Keyword Arguments in pyprocar.bandsplot (Issue #131)

Hi Logan,

I have just tried the older version pyprocar v5.6.6 and I can use the flags as mentioned earlier. But I hope that the developer team can include these flags also in future versions.

Thank you.
