### ISSUE TITLE
Pyprocar Version: 6.1.4,  bandsplot not working

### ISSUE THREAD

**Issue by nayraa78** [romerogroup/pyprocar#132]
Hello,

I've installed the last version of Pyprocar and tried to plot bands but I get the following error, I have no clue what it means.

<img width="900" alt="Screenshot 2023-09-25 at 22 31 45" src="https://github.com/romerogroup/pyprocar/assets/69170083/e855d89d-5a83-4c37-b651-00bda641c524">
<img width="553" alt="Screenshot 2023-09-25 at 22 32 12" src="https://github.com/romerogroup/pyprocar/assets/69170083/049c8f63-5b1e-4e49-8863-0b750e7b22c2">

Thanks for your time!

Nayra

**Comment by lllangWV** [comment]
Hey Nayra,

I am looking at the code now and it direct should have been defined before. A few lines before it checks if the poscar is direct or cartesian. What does your POSCAR look like?

Logan Lang

**Comment by nayraa78** [comment]
Dear Logan,

Yes, the problem was in the POSCAR, it was an indentation error.

Before my POSCAR was:
<img width="418" alt="Screenshot 2023-09-26 at 22 50 17" src="https://github.com/romerogroup/pyprocar/assets/69170083/14a39195-ba9b-4fd2-b969-c0909f65e601">


I had to remove the indentation on the lines 2 and 8. Now, it is:
<img width="473" alt="Screenshot 2023-09-26 at 22 53 00" src="https://github.com/romerogroup/pyprocar/assets/69170083/6cd92945-ab75-493b-b912-61e2c33372c2">

Best,

Nayra
