### ISSUE TITLE
Problem in ticklabel size and tick label scale.

### ISSUE THREAD

**Issue by Sudip9423** [romerogroup/pyprocar#160]
Hi 
I am trying to plot a zoom-in band gap in the range -0.25 to -0.1. The plot is received without any energy tick labels in the y-axis. I checked in the manual, but there is no option except elimit (limit does not set the tick labels in this range). I also tried to modify the plot using matplotlib, but did not work. Can you help me to fix the problem. How to increase the tick label and axis label size, the label size is too small.

**Comment by lllangWV** [comment]
Hey,

I Iooked into this. I think I found a better solution to handle all the matplotlib plotting parameters. Below is an example. 

I added new configuration settings `x_label_params`, `colorbar_label_params`, `major_x_tick_params`, `major_y_tick_params`, `multiple_locator_y_minor_value`, and `multiple_locator_y_major_value`. 

Most of these are dictionaries of settings for their corresponding element. For example,  `x_label_params` is used as input into `ax.set_xlabel`, so here you can add whatever keyword arguments that `set_xlabel` have.

```python
pyprocar.bandsplot(
                    code=code,
                    mode='parametric',
                    # orbitals = [8,9,10,11,12,13,14,15,16,17],
                    fermi=5.3017,
                    orbitals = [4,5,6,7,8],

                    multiple_locator_y_major_value=3,
                    multiple_locator_y_minor_value=0.5,
                    major_y_tick_params={
                            "which": "major",
                            "axis": "y",
                            "direction": "out",
                            "width": 1,
                            "length": 5,
                            "labelright": False,
                            "right": True,
                            "left": True,
                            "labelsize": 20
                        },

                    major_x_tick_params={
                            "which": "major",
                            "axis": "x",
                            "direction": "in",
                            "labelsize": 20
                        },
                    x_label_params={
                        'fontsize':20
                    },
                    colorbar_label_params={'fontsize':30},
                    dirname=data_dir)
```
![image](https://github.com/user-attachments/assets/4d884846-07a8-4ef8-a3ab-d561ce56937d)

I made the change and pushed it to github.

To use these changes, do the following.

```bash
pip uninstall pyprocar
git clone git@github.com:romerogroup/pyprocar.git
cd pyprocar
pip install -e .
```

Does this help?

Logan Lang

**Comment by Sudip9423** [comment]
Hi Logan, Thank you very much for your quick response and kind support, the axis label problem and  label size problem is now solved. But still I have one problem In my zoom -in plot the y-axis ticks are missing. For example, 

import os
import pyprocar

current_dir = os.getcwd()

data_dir = current_dir

pyprocar.bandsplot(
                    code='vasp',
                    mode='plain',
					elimit=[-0.2,-0.12],
                    # orbitals = [8,9,10,11,12,13,14,15,16,17],
                    fermi=-3.3988,
                    #orbitals = [4,5,6,7,8],

                    multiple_locator_y_major_value=3,
                    multiple_locator_y_minor_value=0.5,
                    major_y_tick_params={
                            "which": "major",
                            "axis": "y",
                            "direction": "out",
                            "width": 1,
                            "length": 5,
                            "labelright": False,
                            "right": True,
                            "left": True,
                            "labelsize": 20
                        },

                    major_x_tick_params={
                            "which": "major",
                            "axis": "x",
                            "direction": "in",
                            "labelsize": 20
                        },
                    x_label_params={
                        'fontsize':20
                    },
					y_label_params={
                        'fontsize':20
                    },
                    colorbar_label_params={'fontsize':30},
                    dirname=data_dir)



In this small energy range I have received the plot without y-axis ticks.
![No_y_ticks](https://github.com/user-attachments/assets/546f9ee9-a8ec-414a-813d-f31ba3a593d4)
Can you please look into the matter.

**Comment by Sudip9423** [comment]
Hi Logan, Thank you very much, for the quick response and kind support. This modification has solved my problem. Bellow I have attached a figure for reference, this is exactly what I wanted. Thank you again.
![sample](https://github.com/user-attachments/assets/77efc57f-98f3-4348-9123-679f99e522c4)
