### ISSUE TITLE
Tutorial error using pyprocar.kpath

### ISSUE THREAD

**Issue by Nokimann** [romerogroup/pyprocar#17]
My POSCAR:

azo                                     
   1.00000000000000     
     9.5670000000000002    0.0000000000000000    0.0000000000000000
    -4.7835000000000001    8.2852650380099995    0.0000000000000000
     0.0000000000000000    0.0000000000000000   40.0000000000000000
   Mo   S    H    C    N    O 
    18    35    10    13     2     2
Direct
...

If I tried pyprocar.kpath('POSCAR',40,True,'hpkot',1e-07,1e-05,-1.0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pyprocar/scriptKpath.py", line 21, in kpath
    atoms = np.array(POSCAR[5].split()).astype(np.int)
ValueError: invalid literal for int() with base 10: 'Mo'

It should change from 5 to 6 or not compatible for my POSCAR.

**Comment by uthpalah** [comment]
Dear Nokimann, 

Yes, this is an issue I need to resolve. Currently, it'll work if the "Mo S H C N O" line is omitted from the POSCAR. But I'll get it fixed and update the repo soon. 

Best,
Uthpala

**Comment by uthpalaherath** [comment]
This has been fixed.
