### ISSUE TITLE
Some problem with "disk_io"

### ISSUE THREAD

**Issue by BlessedAkarat** [romerogroup/pyprocar#173]
Hello,  
I am trying to reduce the size of the output folder stored on disk while performing calculations with pw.x.  

I understand that when using the disk_io = 'minimal' option in pw.x, only the converged .xml files are saved, and the rest (like wave function and charge density) are not saved.  
However, it seems that even when I perform the calculations in minimal mode, all the data is still being stored in the output directory. 
[https://www.quantum-espresso.org/Doc/INPUT_PW.html](url) 

> - disk_io
> Specifies the amount of disk I/O activity:
> (only for binary files and xml data file in data directory;
> other files printed at each molecular dynamics / structural
> optimization step are not controlled by this option )
>             
> 'high' :
> save charge to disk at each SCF step,
> keep wavefunctions on disk (in "distributed" format),
> save mixing data as well.
> Do not use this option unless you have a good reason!
> It is no longer needed to specify 'high' in order to be able
> to restart from an interrupted calculation (see [restart_mode](https://www.quantum-espresso.org/Doc/INPUT_PW.html#restart_mode))
>             
> 'medium' :
> save charge to disk at each SCF step,
> keep wavefunctions on disk only if more than one k-point,
> per process is present, otherwise keep them in memory;
> save them to disk only at the end (in "portable" format)
>             
> 'low' :
> save charge to disk at each SCF step,
> keep wavefunctions in memory (for all k-points),
> save them to disk only at the end (in "portable" format).
> Reduces I/O but increases memory wrt the previous cases
>             
> 'nowf' :
> save to disk only the xml data file and the charge density
> at convergence, never save wavefunctions. Restarting from
> an interrupted calculation is not possible with this option.
>             
> 'minimal' :
> save to disk only the xml data file at convergence
>             
> 'none' :
> do not save anything to disk
>             
> Default is 'low' for the scf case, 'medium' otherwise.
> Note that the needed RAM increases as disk I/O decreases

Below is my input.  
Is there any other option I need to change?

**5SCu.scf.in**
```
&CONTROL  
    calculation = 'scf',  
    prefix = '2SCu'  
    restart_mode='from_scratch'  
    pseudo_dir='/scratch/x2929a02/PSlibrary',  
    outdir = './out_2SCu',  
!    dipfield = .TRUE.                                  !dipole correction  
!    tefield = .TRUE.                                   !dipole correction  
    verbosity = 'high'  
    disk_io = 'minimal'	       	       	       	       	!save only xml data file at convergence
!    wf_collect = .TRUE.  
    nstep = 150  
     /  

&SYSTEM  
    ibrav = 0  
    nat = 6  
    ntyp = 1  
!    nbnd = 180  
    ecutwfc = 45,  
    ecutrho = 236,  
!    noncolin = .TRUE.  
!    lspinorb = .TRUE.  
    nspin = 2  
    occupations = 'smearing',  
    smearing = 'gaussian',  
!    smearing = 'marzari-vanderbilt',  
    starting_magnetization(1) = 1.0,  
!    starting_magnetization(2) = 1.0,  
    degauss = 0.0037,
!    edir = 3                                           !dipole correction  
!    emaxpos = 0.6113                                   !dipole correction  
!    eopreg = 0.05183                                   !dipole correction  
!    eamp = 0                                           !dipole correction  
    /  

&electrons  
    mixing_beta = 0.3  
    mixing_mode = 'local-TF'  
!    diagonalization = 'david'  
!    conv_thr = 1.0D-10  
!    electron_maxstep = 100  
!    scf_must_converge = .TRUE.  
     /  

ATOMIC_SPECIES
Cu 63.546 Cu.pbe-dn-kjpaw_psl.1.0.0.UPF

K_POINTS {automatic}  
15 15 15 0 0 0  

CELL_PARAMETERS {angstrom}
  2.5542461872   0.0000000000   0.0000000000
  -1.2771230936   2.2120420856   0.0000000000
  0.0000000000   0.0000000000   27.5131998062

ATOMIC_POSITIONS {angstrom}
Cu     0.00000000     0.00000000     0.00000000
Cu     1.27712313     0.73734738     2.08553336
Cu     0.00000000     1.47469477     4.17106673
Cu     0.00000000     0.00000000     6.25659990
Cu     1.27712313     0.73734738     8.34213326
Cu     0.00000000     1.47469477     10.42766663

```

**5SCu.nscf.in**
```
&CONTROL  
    calculation = 'nscf',  
    prefix = '2SCu'  
    restart_mode='from_scratch'  
    pseudo_dir='/scratch/x2929a02/PSlibrary',  
    outdir = './out_2SCu',  
!    dipfield = .TRUE.                                  !dipole correction  
!    tefield = .TRUE.                                   !dipole correction  
    verbosity = 'high'  
    disk_io = 'minimal'	       	       	       	       	!save only xml data file at convergence
!    wf_collect = .TRUE.  
    nstep = 150  
     /  

&SYSTEM  
    ibrav = 0  
    nat = 6  
    ntyp = 1  
!    nbnd = 180  
    ecutwfc = 45,  
    ecutrho = 236,  
!    noncolin = .TRUE.  
!    lspinorb = .TRUE.  
    nspin = 2  
    occupations = 'smearing',  
    smearing = 'gaussian',  
!    smearing = 'marzari-vanderbilt',  
    starting_magnetization(1) = 1.0,  
!    starting_magnetization(2) = 1.0,  
    degauss = 0.0037,
!    edir = 3                                           !dipole correction  
!    emaxpos = 0.6113                                   !dipole correction  
!    eopreg = 0.05183                                   !dipole correction  
!    eamp = 0                                           !dipole correction  
    /  

&electrons  
    mixing_beta = 0.3  
    mixing_mode = 'local-TF'  
!    diagonalization = 'david'  
!    conv_thr = 1.0D-10  
!    electron_maxstep = 100  
!    scf_must_converge = .TRUE.  
     /  

ATOMIC_SPECIES
Cu 63.546 Cu.pbe-dn-kjpaw_psl.1.0.0.UPF

K_POINTS {automatic}  
150 150 4 0 0 0  

CELL_PARAMETERS {angstrom}
  2.5542461872   0.0000000000   0.0000000000
  -1.2771230936   2.2120420856   0.0000000000
  0.0000000000   0.0000000000   27.5131998062

ATOMIC_POSITIONS {angstrom}
Cu     0.00000000     0.00000000     0.00000000
Cu     1.27712313     0.73734738     2.08553336
Cu     0.00000000     1.47469477     4.17106673
Cu     0.00000000     0.00000000     6.25659990
Cu     1.27712313     0.73734738     8.34213326
Cu     0.00000000     1.47469477     10.42766663

```
![image](https://github.com/user-attachments/assets/0039d28c-8c62-49ae-aeb1-0531f28af57f)

**Comment by BlessedAkarat** [comment]
**Some edit to the above content.**

I tested it a few more times, but it seems like the wfc is not being saved when using the disk_io option. There might be an error in that calculation, so it seems like disk_io wasn't applied (I really don't know why...).

However, it seems that the `wfcdw.dat` files saved in the `.save` directory under the output directory keeps being saved. Is there no way to stop this from being saved? I think with the minimal option, even this should not be saved, and only the `.xml` file should be saved...

**Comment by ahromero** [comment]
This is a question for the QE developers. Sorry, our package only uses the output QE produces.


______________________________________::::__________________________________________
Prof. Aldo Humberto Romero
Director Research Computing, West Virginia University
Eberly Family Distinguished Professor
Fellow American Physical Society
Editor Physica B, Assistant Editor EPJB, Editor Frontiers in Physics
Section Editor Papers in Physics
Member of the Editorial Board of  “Materials” and “Symmetry Physics”
https://scholar.google.com/citations?user=pwte-hQAAAAJ&hl=en

Physics and Astronomy Department
West Virginia University
135 Willey Street, PO Box 6315
111 White Hall
Morgantown, WV 26506
Phone:  304-293-6317
Fax:  304-293-5732
email: ***@***.***


From: BlessedAkarat ***@***.***>
Date: Thursday, December 19, 2024 at 12:21 AM
To: romerogroup/pyprocar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [romerogroup/pyprocar] Some problem with "disk_io" (Issue #173)

Some edit to the above content.

I tested it a few more times, but it seems like the wfc is not being saved when using the disk_io option. There might be an error in that calculation, so it seems like disk_io wasn't applied (I really don't know why...).

However, it seems that the wfcdw.dat files saved in the .save directory under the output directory keeps being saved. Is there no way to stop this from being saved? I think with the minimal option, even this should not be saved, and only the .xml file should be saved...

**Comment by BlessedAkarat** [comment]
First of all, thank you for your attention. @ahromero and @lllangWV.

I momentarily forgot that this is a place for the extension of Quantum ESPRESSO, called pyprocar.
Yes, it is completely my mistake.
I think I confused the forum and made an incorrect inquiry.

I am really sorry for taking your precious time.
Sincery.
