### ISSUE TITLE
Spin separated band non-collinear

### ISSUE THREAD

**Issue by MIraola** [romerogroup/pyprocar#23]
Hello,

I have the outputs of a non-collinear calculation with spin-orbit coupling and I want to plot separately the bands of Sz=up and Sz=down (although I know they aren't good quantum numbers). I see in the documentation that .filter() function can be used to separate the up/down contributions, but I was wondering if those lines should be followed in the same way for both collinear and non-collinear calculations. Should dI use the following lines?

pyprocar.filter('PROCAR','PROCAR-up',spin=[0])
pyprocar.bandsplot('PROCAR-up',spin=3)

Thank you for your help.

**Comment by fvmunoz** [comment]
Hi Mikel,

In your first line you need to put spin=3,
That is Sz.

In the second line you need to put spin=0 (it is the first entry of the
sipn block, actually the only value for spin)

But you wont get separated spin up from down. You will need to tweak the
code. Is not that hard... Search in the code for the "bandsplot", in some
line there will appear something about "spd". It is a numpy array. You need
to select the up/down components there.

I have no access to a computer now. So I migth be somewhat inaccurate. Tell
me if you need help with anything.

Best regards
Francisco
