### ISSUE TITLE
Fermi3D

### ISSUE THREAD

**Issue by warda-rahim** [romerogroup/pyprocar#24]
Hi, 
I have been trying to plot 3D fermi surface using my PROCAR and OUTCAR from a VASP hybrid band structure calculation. Pyprocar.repair works fine. However, when I try pyrocar.fermi3D, it gives me the error shown below:

```
Plotting band 0
Traceback (most recent call last):
  File "/home/zccappr/.local/bin/procar", line 815, in <module>
    args.func(args)
  File "/home/zccappr/.local/bin/procar", line 120, in call_fermi3D
    kwargs = args.kwargs)
  File "/home/zccappr/.local/lib/python3.6/site-packages/pyprocar/scriptFermi3D.py", line 463, in fermi3D
    mapped_func,kpoint_matrix = mapping_func(kvector,eigen)
  File "/home/zccappr/.local/lib/python3.6/site-packages/pyprocar/scriptFermi3D.py", line 54, in mapping_func
    if len(bands[tot_cond]) != 0 :
IndexError: boolean index did not match indexed array along dimension 0; dimension is 304 but corresponding boolean dimension is 311
```

I tried it with different structures and for each I got the same error with a difference of 7 between the numbers in **IndexError: boolean index did not match indexed array along dimension 0; dimension is 304 but corresponding boolean dimension is 311**. 

I am using **pyprocar.fermi3D(PROCAR, OUTCAR, bands=-1, scale=1, mode='plain', st=False)**
Secondly, for some reason it is also finding the wrong number of ions. I have 24 ions in my POSCAR but it finds 25.
I am attaching my PROCAR, OUTCAR, POSCAR and KPOINTS files. 

[PROCAR.zip](https://github.com/romerogroup/pyprocar/files/4138755/PROCAR.zip)
[OUTCAR.zip](https://github.com/romerogroup/pyprocar/files/4138765/OUTCAR.zip)
[POSCAR.zip](https://github.com/romerogroup/pyprocar/files/4138767/POSCAR.zip)
[KPOINTS.zip](https://github.com/romerogroup/pyprocar/files/4138768/KPOINTS.zip)

Thank you.

**Comment by petavazohi** [comment]
You need to turn off the symmetry in your calculation. set ISYM = -1

**Comment by petavazohi** [comment]
also do not use a Gamma centered K-mesh

**Comment by warda-rahim** [comment]
Hi,

Thank you very much for your response. I will repeat the band structure calculation with symmetry turned off.

Is there a special reason for not using Gamma centered k-meshes? Does the code only work with non-Gamma centred meshes?

Regards,
Warda



On 3 Mar 2020, at 12:35, Pedram Tavadze <notifications@github.com<mailto:notifications@github.com>> wrote:


also do not use a Gamma centered K-mesh

**Comment by petavazohi** [comment]
The way the Gamma centered kmesh is generated is usually similar to this (-0.45,-0.4,...,0,...,0.45,0.5). Now the sampling of k-space is not symmetric. While this is sampling the whole BZ, the fermi surface generated will be covering some parts from the 2nd BZ in the positive side of the K-space and missing the same parts from the 1st BZ in the negative side. We have a function in the Fermi3D script that symmetrizes the sampling but this usually leads to unreal artifacts on the edges of the BZ. The best option is to use a Monkhost-Pack mesh. Is there a specific reason you want to use Gamma centered?

**Comment by warda-rahim** [comment]
Hi,

I normally use Gamma centred meshes because it gives a good description of the band character at Gamma point as often the band gap is present there, but since this structure is a semimetal so it should not be an issue. I have resubmitted the calculation with Monkhorst-Pack and with symmetry turned off. Hopefully, it will work this time.
Thank you!

Regards,
Warda




On 4 Mar 2020, at 19:49, Pedram Tavadze <notifications@github.com<mailto:notifications@github.com>> wrote:


The way the Gamma centered kmesh is generated is usually similar to this (-0.45,-0.4,...,0,...,0.45,0.5). Now the sampling of k-space is not symmetric. While this is sampling the whole BZ, the fermi surface generated will be covering some parts from the 2nd BZ in the positive side of the K-space and missing the same parts from the 1st BZ in the negative side. We have a function in the Fermi3D script that symmetrizes the sampling but this usually leads to unreal artifacts on the edges of the BZ. The best option is to use a Monkhost-Pack mesh. Is there a specific reason you want to use Gamma centered?
