### ISSUE TITLE
Bug in procarparser.py

### ISSUE THREAD

**Issue by SiyuChen** [romerogroup/pyprocar#28]
I am trying using the package to unfold a 9x9x1 supercell band, and I encountered the following error:
self.procar.readFile2(self.fname, phase=True, ispin=ispin)
  File "/u/fs1/.local/lib/python3.6/site-packages/pyprocar/procarparser/procarparser.py", line 688, in readFile2
    iband = int(ss[1]) - 1
ValueError: invalid literal for int() with base 10: '***'

I think this is due to the fact that the code does not realise that VASP does not write down the band index beyond 999.  For example, my PROCAR looks like:

band 998  # energy    -0.2155885  # occ.  0.00000000

ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    tot
  1  0.000  0.001  0.001  0.001  0.000  0.000  0.000  0.000  0.000  0.003
  2  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.002
  3  0.000  0.001  0.001  0.001  0.000  0.000  0.000  0.000  0.000  0.004
....

band 999 # energy   -0.19090405 # occ.  0.00000000

ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    tot
  1  0.000  0.000  0.002  0.000  0.000  0.000  0.000  0.000  0.000  0.003
  2  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.002
  3  0.000  0.001  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.002
....

band *** # energy   -0.18754690 # occ.  0.00000000

ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    tot
  1  0.000  0.000  0.001  0.001  0.000  0.000  0.000  0.000  0.000  0.003
  2  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.002
  3  0.000  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.002
....

band *** # energy   -0.17669861 # occ.  0.00000000

ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    tot
  1  0.000  0.003  0.001  0.001  0.000  0.000  0.000  0.000  0.000  0.006
  2  0.000  0.001  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.002
  3  0.000  0.002  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.004
....

Could you please fix this bug? Thanks.

**Comment by mailhexu** [comment]
Hi, 
Thanks for the information. A quickfix is in the master branch. 
HeXu
