### ISSUE TITLE
Potential dependency conflicts between pyprocar and numpy

### ISSUE THREAD

**Issue by NeolithEra** [romerogroup/pyprocar#31]
Hi, as shown in the following full dependency graph of **_pyprocar_**, **_pyprocar_** requires **_numpy ==1.17.2_**, **_pyprocar_** requires **_matplotlib *_** (**_matplotlib 3.2.1_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_matplotlib 3.2.1_** transitively introduces **_numpy >=1.11_**.

Obviously, there are multiple version constraints set for **_numpy_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_numpy 1.17.2_** (i.e., the newest version satisfying constraint **_==1.17.2_**) is the actually installed version.

Although the first found package version **_numpy 1.17.2_** just satisfies the later dependency constraint （**_numpy ==1.17.2_**), such installed version is very close to the upper bound of the version constraint of numpy specified by **_matplotlib 3.2.1_**. 

Once **_matplotlib_** upgrades，its newest version will be installed, as **_pyprocar_** does not specify the upper bound of version constraint for **_matplotlib_**. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_matplotlib_** version introduces a higher version of **_numpy_**, violating its another version constraint **_==1.17.2_**.

According to the release history of matplotlib, it habitually upgrates Numpy in its recent releases. For instance, matplotlib #15645 upgrated Numpy’s constraint from **_>=1.11 to >=1.12_**, and matplotlib #15698 upgrated Numpy’s constraint from **_>=1.12 to >=1.15_**. 

As such, it is a warm warning of a potential dependency conflict issue for pyprocar.

### Dependency tree
```
pyprocar - 5.2.1
| +- ase(install version:3.19.1 version range:*)
| | +- matplotlib(install version:3.2.1 version range:*)
| | | +- cycler(install version:0.10.0 version range:>=0.10)
| | | | +- six(install version:1.14.0 version range:*)
| | | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | | +- numpy(install version:1.17.2 version range:>=1.11)
| | | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| | +- numpy(install version:1.17.2 version range:*)
| | +- scipy(install version:1.4.1 version range:*)
| +- matplotlib(install version:3.2.1 version range:*)
| | +- cycler(install version:0.10.0 version range:>=0.10)
| | | +- six(install version:1.14.0 version range:*)
| | +- kiwisolver(install version:1.2.0 version range:>=1.0.1)
| | +- numpy(install version:1.17.2 version range:>=1.11)
| | +- pyparsing(install version:3.0.0a1 version range:>=2.0.1)
| | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| +- mayavi(install version:4.6.2 version range:==4.6.2)
| +- numpy(install version:1.17.2 version range:==1.17.2)
| +- pyfiglet(install version:0.8.post1 version range:*)
| +- scikit-image(install version:0.16.2 version range:*)
| +- scipy(install version:1.4.1 version range:==1.4.1)
| +- seekpath(install version:1.9.5 version range:>=1.0)
| | +- future(install version:0.18.2 version range:>=0.15)
| | +- numpy(install version:1.17.2 version range:>=1.0)
| | +- spglib(install version:1.14.1.post0 version range:>=1.14.1)
| | | +- numpy(install version:1.17.2 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.17.2_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_matplotlib_**.
3.	Change your direct dependency **_matplotlib_** to be **_<=3.2.1_**.
@uthpalaherath  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_numpy_** to be **_>=1.17.2_**.
2.	Remove your direct dependency **_numpy_**, and use the **_numpy_** transitively introduced by **_matplotlib_**.
3.	Change your direct dependency **_matplotlib_** to be **_<=3.2.1_**.
@uthpalaherath  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by uthpalaherath** [comment]
Hello @NeolithEra, 

Thank you for your suggestions. I think I set the constraints a couple months ago to do some testing of different versions. I'll update the dependencies requirements in the next release. 

Thanks again, 

Best, 
Uthpala
