### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by jan-janssen** [romerogroup/pyprocar#34]
Hi, 

I recently create the `pyprocar` conda forge package, now it is possible to install 
PyProcar via:
```
conda install -c conda-forge pyprocar
```
I was wondering if one of the core developers is interested in joining me in maintaining the package. 

Best, 

Jan

**Comment by uthpalaherath** [comment]
Hello Jan,

This is great!
I'll contact you via email and we can discuss more. 

Thanks,

Best,
Uthpala
