### ISSUE TITLE
DOS qe plot failed

### ISSUE THREAD

**Issue by IsmaelDiouFY** [romerogroup/pyprocar#77]
Hi Dears,
Someone can help me please to resolve the error of DOS plot, calculate by DFT.
![Capture](https://user-images.githubusercontent.com/74740656/180342913-f54a3eea-d650-4502-a11f-5c2e7f0f3297.PNG)
![Capture1](https://user-images.githubusercontent.com/74740656/180343108-9074ca1b-6d85-46af-a83f-7660b9d69dba.PNG)

**Comment by lllangWV** [comment]
Hey IsmaelDiouFY,

sorry for the late reply. I have 2 suggestions for a solution. 

1.  This version is old and the parsing method has changed to use the .xml file instead. I refer you to the following page https://romerogroup.github.io/pyprocar/dftprep.html#quantum-espresso, this will tell you what you need to do for the density of states calculation
2. The second suggestion would be to send me the .in file you used and the pseudopotentials, then I can take a look at where the issue is coming from. If I had to guess, the issue is coming from the parsing.

Logan Lang

**Comment by IsmaelDiouFY** [comment]
Hi Lang,
Thank you for your reply. Of course, I used the atomic_proj.xml, charge-density.dat and data-file-schema.xml files in the directory where I ran propycar. I have attached a drobox link to the inputs files.

https://www.dropbox.com/t/n8VMw5fwmddnmAB8

**Comment by IsmaelDiouFY** [comment]
Hi Lang, 
I forgot to tell you about two things:
The first is that when I ran pyprocar in Jupyter Notebook, the processing take a lot off time before to give me the error (some time 2hours).
![image](https://user-images.githubusercontent.com/74740656/181120860-15fd73c4-0151-4d62-acf7-ed04d19c6051.png)
The second is, when i tried to do the Fe tuto from pyprocar example, it's give me a bad result after 2hours processing. 
![Fe-qe-6 7(b)_LI](https://user-images.githubusercontent.com/74740656/181121525-fe823dda-470c-44cf-95ef-365cb69fe17b.jpg)
To limit the processing time, I was already using the pyprocar filter but it's the same (the processing takes several hours). Can you tell me how well can I use the pyprocar filter for QE? Which files (scf.out, bands.out or kpdos.out) should I run pyprocar-filter with? Or should I use it on all three output files? After, for example, if I run pyprocar-filter to reduce kpoints, should I delete the first input file used to create a pyprocar-out filter, before running pyprocar in the same directory? Can you show me a good command to run pyprocar with QE to reduce bands and Kpoints together and plot after bands are reduced?
If you have any suggestions for speeding up the processing, please let me know.
Thanks a lot!

**Comment by lllangWV** [comment]
Hey IsmaelDiouFY,

I am terribly sorry for the late 2-week response. I got swamped with other projects. Okay, so the version of pyprocar you are using is depreciated for using quantum espresso. That version uses regex to parse the kpdos.out file to get the projects and kpoints, this is inefficient. In the version on github, we parse everything from the .xml files making it much more efficient. So I suggest to use the version on github

I ran your calculation with the following code:
**import pyprocar
pyprocar.bandsplot(dirname = 'issues/Ismael/bands',elimit = [-20,20], mode='plain', color = 'blue', code='qe')**

As you can see in this version, you have to specify where the calculation took place with "dirname"

![image](https://user-images.githubusercontent.com/64661090/183783246-2e6ee878-cc5d-418f-99a2-a59b1288a6d4.png)

And for the density of states:
**pyprocar.dosplot(dirname = 'issues/Ismael/dos',elimit=[-20,20], mode='plain', code='qe')**

![image](https://user-images.githubusercontent.com/64661090/183967112-d47d1928-a193-43a7-85b1-1eda702cafb5.png)

And for bandsdosplot:
**pyprocar.bandsdosplot(dos_dirname = 'issues/Ismael/dos',bands_dirname = 'issues/Ismael/bands', bands_mode='plain',dos_mode='plain', code='qe')**

![image](https://user-images.githubusercontent.com/64661090/183969907-43eddb19-0a6a-4b9c-aa9e-ea0d33757550.png)

**Comment by IsmaelDiouFY** [comment]
Hi,
Thanks !
I reinstalled pyprocar with version (5.6.5) from github. However after
running pyprocar, I still get an error message.
[image: image.png]
Can you please share your quantum-espresso input files?

**Comment by lllangWV** [comment]
Interesting, what was the error? 

Here are the files for the bands and dos:

[dos.zip](https://github.com/romerogroup/pyprocar/files/9306229/dos.zip)
[bands.zip](https://github.com/romerogroup/pyprocar/files/9306222/bands.zip)

**Comment by IsmaelDiouFY** [comment]
Hi,
Thanks for the input files.
I again recalculated the bands and DOS using the input files you sent me. I keep getting the error like <<AttributeError: 'Settings' object has no attribute 'general>> (see picture). I installed this version of pyprocar (https://github.com/romerogroup/pyprocar), is it the one you suggested?
Do I need to install required-libraries for reading .xml files?
![Capture11](https://user-images.githubusercontent.com/74740656/184263327-f39ed2d2-a0ed-474a-90e8-5d4427e910c1.PNG)
![image](https://user-images.githubusercontent.com/74740656/184263343-e531c27e-70ca-4aff-a690-d8242612d911.png)

**Comment by IsmaelDiouFY** [comment]
Hi,
Thanks for the input files.
I again recalculated the bands and DOS using the input files you sent me. I keep getting the error like <<AttributeError: 'Settings' object has no attribute 'general>> (see picture). I installed this version of pyprocar (https://github.com/romerogroup/pyprocar), is it the one you suggested?
Do I need to install required-libraries for reading .xml files?

![image](https://user-images.githubusercontent.com/74740656/184263384-34cb3c57-33a1-4446-939f-0a1c7c48153f.png)

**Comment by lllangWV** [comment]
That is strange. 'settings' should have an attribute general. Where you clone the repository, do you have the following file pyprocar/pyprocar/utils/default_settings.ini? And inside that file, is there a section tag called 'general'?

**Comment by lllangWV** [comment]
Wait, do you try to install the v5.6.3? 
![image](https://user-images.githubusercontent.com/64661090/184266907-3f8ea2e9-4b12-4281-a88a-913e62865b0b.png)

If so, this is the wrong version. Can you clone the repository directly?

![image](https://user-images.githubusercontent.com/64661090/184266989-9ab468bc-bb26-4fef-b567-bc1723ef2fea.png)

**Comment by IsmaelDiouFY** [comment]
Hi, 
Yes i find a section tag called 'general' in pyprocar/pyprocar/utils/default_settings.ini:
image.png
Yes I installed the version https://github.com/romerogroup/pyprocar.git, but after the installation, it is the version 5.6.5 which is displayed not 5.6.3.



image.png

**Comment by IsmaelDiouFY** [comment]
Hi, 
Yes i find a section tag called 'general' in pyprocar/pyprocar/utils/default_settings.ini:

![image](https://user-images.githubusercontent.com/74740656/184449640-1b8f5c00-d387-49a9-b9ff-1c595bd877e2.png)


Yes I installed the version https://github.com/romerogroup/pyprocar.git, but after the installation, it is the version 5.6.5 which is displayed not 5.6.3.

![image](https://user-images.githubusercontent.com/74740656/184449592-583bef27-b4ba-4635-b426-249001201ea2.png)

**Comment by lllangWV** [comment]
Okay, so I tried to install pyprocar on a fresh virtual machine. I was able to generate the band structure and the density of states without generating your error.

I am trying to see why this issue is coming up. It could be a weird behavior with jupyter notebooks, but I am not sure. My next suggestion is to use the package outside the jupyter notebooks.

If all else fails, uninstall and reinstall it from scratch. I usually like making a conda environment with python==3.8, then installing pyprocar from the directory where I cloned it to.

Logan Lang

**Comment by IsmaelDiouFY** [comment]
Thank you for your reply. I uninstalled anaconda and all python packages.
Then reinstall anaconda by creating an environment: conda create --name
jupy python=3.8 ipykernel.
I then installed pyprocar: python setup.py install.
After running pyprocar on Anaconda-Powershell-prompt, I get the same
message: AttributeError: 'Settings' object has no attribute 'general'

[image: image.png]

**Comment by IsmaelDiouFY** [comment]
Hi Dear,
I wanted to point out that pyprocar for band structure tracking works fine
for all three latest versions of purpocar with qe.7.0 and qe.6.5.
The problem was related to the use of mpirun .... -nk 4....($PW_COMMAND
$infile -nk 4 | tee $outfile). With the removal of -nk 4 I no longer get
the error AttributeError: 'Settings' object has no attribute 'general'.
However, for DOS I get with all versions of pyprocar, the following error
for collinear spin calculations: [File
"D:\Users\ikoun\Desktop\shared\Mn10Ge6\dos7\qe_dos_example.py", line 12, in
<module>
    pyprocar.dosplot(code='qe',elimit=[-95,10],orientation='vertical',
mode='plain')
  File
"C:\Users\ikoun\anaconda3\lib\site-packages\pyprocar\scriptDosplot.py",
line 388, in dosplot
    vaspxml = QEDOSParser(nscfin="nscf.in",
  File
"C:\Users\ikoun\anaconda3\lib\site-packages\pyprocar\qeparser\qe_dos_parser.py",
line 99, in __init__
    self.data = self.read()
  File
"C:\Users\ikoun\anaconda3\lib\site-packages\pyprocar\qeparser\qe_dos_parser.py",
line 113, in read
    return self.parse_pdos()
  File
"C:\Users\ikoun\anaconda3\lib\site-packages\pyprocar\qeparser\qe_dos_parser.py",
line 581, in parse_pdos
    dos[:,2:5,0] = final_dos[:,1:]
ValueError: could not broadcast input array from shape (8831,7) into shape
(8831,3)].
However, for non-spin polarized computation, pyprocar plots the back very
well without error.

**Comment by lllangWV** [comment]
- The problem was related to the use of mpirun .... -nk 4....($PW_COMMAND $infile -nk 4 | tee $outfile). With the removal of -nk 4 I no longer get the error AttributeError: 'Settings' object has no attribute 'general'.

This is strange, I do not understand how running mpirun on inputs would be affecting an external python package (pyprocar). But hey, if it works that is good. Glad to know about this issue. I will discuss this with our collaborators to understand it more.

Now, as for the DOS. I see the pyprocar you are using is using QEDOSParser. This is an old parser. Could you use the pyprocar on the GitHub?  I think I already asked you to do this, so I am sorry if I am being repetitive.  If this problem still persists, we could talk over zoom or discord to work this problem out.

**Comment by IsmaelDiouFY** [comment]
Hi,
Thanks for your reply.
Of course, I used pyprocar from github, i sent you my input files.

https://www.dropbox.com/s/3lyoyyq5funm0ts/dos.rar?dl=0

**Comment by lllangWV** [comment]
I think it would be easier to talk over zoom about this. When is the best time for you to talk? My schedule is pretty flexible.

**Comment by IsmaelDiouFY** [comment]
Hi dear,
Yes of course, if is okay for you we can talk tomorrow…

**Comment by lllangWV** [comment]
Sure. What time can you talk? My zoom link is http://wvu.zoom.us/my/physics112.logan

**Comment by IsmaelDiouFY** [comment]
Thanks ! I will be free tomorrow 25/08 at 11:00 Am.

**Comment by lllangWV** [comment]
11:00 A.M Eastern Standard Time? Just making sure

**Comment by IsmaelDiouFY** [comment]
Sory, i forgot that you are not in France. 11h from Greenwich time (GMT) it
is okay for you?

**Comment by lllangWV** [comment]
That time works for me! I'll see you then.

**Comment by IsmaelDiouFY** [comment]
Okay! I am free now so if you are okay my zoom link is
***@***.*** See you !

**Comment by lllangWV** [comment]
I can't see what your zoom link is. Mine is http://wvu.zoom.us/my/physics112.logan

**Comment by IsmaelDiouFY** [comment]
Hi,
Yes i find a section tag called 'general' in
pyprocar/pyprocar/utils/default_settings.ini:
[image: image.png]

Yes I installed the version https://github.com/romerogroup/pyprocar.git,
but after the installation, it is the version 5.6.5 which is displayed not
5.6.3.


[image: image.png]
