### ISSUE TITLE
Plot 2D spin-texture Error: cannot import name '_ccallback_c' from 'scipy._lib' 

### ISSUE THREAD

**Issue by Yang-Jun-tao** [romerogroup/pyprocar#9]
Dear Uthpala:
   Hi!
   I am now learning your great tool PyProcar.
  When I want to plot the fermi2D spin-texture, there is an error:
   ---  ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (C:\Users\user\AppData\Roaming\Python\Python37\site-packages\scipy\_lib\__init__.py)

  I have installed and upgrade the SciPy, but the error remains.

  So, please, how can I solve this problem?

**Comment by uthpalah** [comment]
Dear Yang-Jun-tao,

Thank you for using PyProcar. Can you please send me your PROCAR file and OUTCAR and the command you were trying to execute?
I can take a look.

Thank you,

Best, 
Uthpala

**Comment by Yang-Jun-tao** [comment]
Dear Uthpalah,
  Thanks for your comments.
  I have solved the problems that caused by the conflict between  conda and python "cannot import name '_ccallback_c' from 'scipy.lib' " .

 But now, there is a new problem. Following is my command and output，
 
 **$pyprocar.filter('PROCAR','PROCAR-d',orbitals=[5,6,7,8,9])**

   Input file  : PROCAR
Output file : PROCAR-d
atoms       : None
orbitals  : [5, 6, 7, 8, 9]
orb. names  : None
bands       : None
spins       : None
Manipulating the orbitals
New orbitals names (default):  ['o0', 'o1', 'o2', 'o3', 'o4']

  **$pyprocar.fermi2D('PROCAR-r',outcar='OUTCAR',energy=-5,st=True, spin=1)**

   file            :  PROCAR-r
atoms           :  [-1]
orbitals        :  [-1]
spin comp.      :  1
energy          :  -5
fermi energy    :  None
Rec. basis      :  None
rot. symmetry   :  1
origin (trasl.) :  [0, 0, 0]
rotation        :  [0, 0, 0, 1]
masking thres.  :  None
save figure     :  None
outcar          :  OUTCAR
st              :  True
no_arrows       :  False
Fermi energy found in outcar file = -2.9256
ProcarParser::WARNING: 6 orbitals. (Some of) They are unknow (if you did 'filter' them it is OK).
ProcarParser::WARNING: 6 orbitals. (Some of) They are unknow (if you did 'filter' them it is OK).
ProcarParser::WARNING: 6 orbitals. (Some of) They are unknow (if you did 'filter' them it is OK).
ProcarParser::WARNING: 6 orbitals. (Some of) They are unknow (if you did 'filter' them it is OK).
ProcarParser::WARNING: 6 orbitals. (Some of) They are unknow (if you did 'filter' them it is OK).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyprocar\scriptFermi2D.py", line 77, in fermi2D
    data.selectIspin([i])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyprocar\procarselect\procarselect.py", line 97, in selectIspin
    self.spd = self.spd[:,:,value]
IndexError: index 2 is out of bounds for axis 2 with size 2


As you see, there is an indexError, how to solve it?

Thanks!

Attacjhed please find is my files.

[MnPSe3.zip](https://github.com/romerogroup/pyprocar/files/2965561/MnPSe3.zip)
